### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by jenkennedy** [carlosdelaomartinez/OkayCutePaw#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- [x] Lets move messaging to MVP number 6.  It will be more involved and you'll be learning a new technology so it will be helpful to get a few full feature reps in before tackling that one so you are better prepped for it!

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
- [x] rename Question Joins Table to something like `question_answers`
- [x] add `quizzes` table if we are associating questions with specific quizzes (foreign key of `quiz_id` in the `questions` table
- [x] remove `question_id` on the `questions` table since we have the `id` column already

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
- [x] wrap _all_ of the state shape in the triple backticks with 'javascript' following the opening triple backticks to format nicely
- [x] lets rename the `questions_answers` table to `question_answers`

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by jenkennedy** [comment]
Left some comments above for the docs you've completed so far.  Let me know if you have any questions!

**Comment by carlosdelaomartinez** [comment]
Thanks! I went through these and have updated the files, I am still a bit unsure on the messaging backend routes/state. Thanks for the help, I look forward to your feedback!

**Comment by jenkennedy** [comment]
Just reviewed again! Looking better! Look over all the remaining unchecked boxes and make necessary updates.  Slack me if you have a question about any of them and we can address them in our meeting on Monday.

As for the backend routes, we need to make sure at least one of your features gets the full CRUD cycle (Create, Read, Update, Delete).  I'm thinking that might be most doable for messages.  What do you think?

**Comment by jenkennedy** [comment]
- [ ] Add example data in sample state for `questions` and `question_answers`

**Comment by carlosdelaomartinez** [comment]
Thanks, the example data has been added into the sample state.
